# Generated by Django 5.1.3 on 2024-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='propertyimages')),
                ('property_type', models.CharField(choices=[('house', 'house'), ('land', 'land'), ('appartment', 'appartment')], default='house', max_length=200)),
                ('bedroom_count', models.PositiveIntegerField()),
                ('square_footage', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
